# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: selfhosted

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  condition: 
   
  # Download the Databricks CLI.
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      winget search databricks
      winget install Databricks.DatabricksCLI










      # Deploy the bundle to the "dev" target as defined
      # in the bundle's settings file.
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'databricks bundle deploy'
    bashEnvValue: '${env:SP_TOKEN}'
      